### ISSUE TITLE
"no viable description in reply" from text between asterisks

### ISSUE THREAD

**Issue by qcezwsx** [Brawlence/texgen-webui-SD_api_pics#6]
for example if there is only an action description in response , like `*You're standing right outside the adventurer guild, what do you want to do?*`
You will get `no viable description in reply, try regenerating` as an answer from the bot.

That makes it unusable in RPG style bots. It's very sad because they are like made for each other with adventure mode. 

Maybe there is a workaround?

**Comment by Brawlence** [comment]
Yes, there's a workaround. Currently any text in between `*` asterics `*` gets cleaned out; you can disable it by commenting out `string = remove_surrounded_chars(string)` in the function `def output_modifier(string)`

**Comment by Brawlence** [comment]
The needed string is located [here](https://github.com/Brawlence/SD_api_pics/blob/799e4877ff1c8ce8df05c6b22f7f535de397f4a0/script.py#L195) if you use this repository script OR [here](https://github.com/oobabooga/text-generation-webui/blob/main/extensions/sd_api_pictures/script.py#L202C5-L202C45) if you use the ooba's included version.

**Comment by Brawlence** [comment]
TODO: make a toggle to change this behaviour via UI?
